name: Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest  # Cambia a macos-latest si prefieres Mac
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - run: pnpm install --frozen-lockfile
      - run: cd tests && pnpm install --frozen-lockfile
      - uses: actions/cache@v3  # Cache para navegadores de Playwright
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: npx playwright install  # Instala navegadores para tests
      - run: cd tests && npx vitest run --browser  # Ejecuta tests en navegador