name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install  # Install dependencies for gdb
      - run: npm run build  # Build the bundle to dist/index.js
      - run: cd tests && npm install  # Install dependencies for tests
      - run: cd tests && npm test  # Run tests from gdb/tests